[supervisord]
nodaemon=true

[program:X11]
command=/usr/bin/Xvfb :0 -screen 0 1920x1080x24
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:x11vnc]
command=/usr/bin/x11vnc -noxrecord
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:novnc]
command=/root/novnc/utils/novnc_proxy --listen 8080 --vnc localhost:5900
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:startup]
command=/bin/bash -c /startup.sh
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:fluxbox]
command=/usr/bin/fluxbox
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true